service: serverless-rekognition

provider: 
  name: aws
  runtime: nodejs8.10
  stage: test
  environment:
    ACCESS_KEY_ID: ${file(./serverless.env.yml):prd.ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${file(./serverless.env.yml):prd.SECRET_ACCESS_KEY}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  rekognition:
    handler: src/api.default
    events:
      - http: ANY /
      - http: 'ANY {proxi+}'

custom:
  webpackIncludeModules:
    forceInclude:
      - request
